Bug/dk 233
givtnl/givt-app-kids pull request #34
Opened 2023-02-21 13:11 UTC by Daniela510

Replace app png files wit svg files in order to remove blur.

2023-02-21 15:22 UTC, alexbejann commented on lib/screens/profile_selection_screen.dart
> +      if (!mounted) return;
Love it! :D

2023-02-21 15:22 UTC, alexbejann approved these changes

2023-02-21 15:48 UTC, pavelpavelko requested changes

2023-02-21 17:54 UTC, Daniela510 commented on pubspec.yaml
> -    - assets/lotties/confetti.json
yes that was an oversight. Fixed now

2023-02-22 08:48 UTC, MaikelStuivenberg approved these changes

2023-02-22 08:51 UTC, merged